// Merges the three generated JSON files into docs/data.js, the one file the app
// actually loads. Run this last, after build-quests.js / build-trees.js /
// build-craftables.js have all produced their JSON.
//
//   node scripts/merge-data.js
const fs = require("fs"), path = require("path");

const docs = path.join(__dirname, "..", "docs");
const read = name => {
  const p = path.join(docs, name);
  if (!fs.existsSync(p)) { console.error(`ABORT: missing ${p} — run its generator first`); process.exit(1); }
  return JSON.parse(fs.readFileSync(p, "utf8"));
};

const quests = read("data-quests.json");
const trees = read("data-trees.json");
const craftables = read("data-craftables.json");
const hornSongs = read("data-horn-songs.json");

const out = {
  keyTiers: quests.keyTiers,
  urgentChain: quests.urgentChain,
  victory: quests.victory,
  classes: trees,
  craftables,
  hornSongs,
};

const OUT = path.join(docs, "data.js");
fs.writeFileSync(OUT,
  "// Generated by scripts/build-quests.js + build-trees.js + build-craftables.js +\n" +
  "// build-horn-songs.js + merge-data.js.\n" +
  "// Do not hand-edit — re-run the generators and this script instead.\n" +
  "window.MHGU_CHALLENGE_DATA = " + JSON.stringify(out) + ";\n");
console.log(`wrote ${OUT} — ${quests.keyTiers.length} key tiers, ${quests.urgentChain.length}-step urgent chain, ` +
  `${trees.length} classes, ${craftables.length} craftables, ` +
  `${Object.keys(hornSongs).length} horn note combos`);
console.log("Remember to bump ?v= on data.js in docs/index.html.");
