// Checks docs/data-trees.json's branch links (`p`) against mhgu-collection-tracker's
// own `parents` maps — the actual ground truth those links are derived from
// (mhgu.db's `parent_id` column, by way of build-data.mjs). build-trees.js just
// copies `p` verbatim from mhgu-weapon-trees' WDATA; nothing gates that copy
// against drift once a life is running, and data-trees.json is regenerated by
// hand, not on every collection-tracker change — so this exists to catch the
// gap: a run started against a stale data-trees.json (or an upstream extraction
// bug) would show a weapon as its own tree when it should branch off another,
// with nothing here to say so.
//
//   node scripts/verify-trees.js [pathToCollectionTrackerMaterialsDir]
//
// Exits non-zero on any mismatch so this can gate a build/commit later, not
// just be read by hand.
const fs = require("fs"), path = require("path");

const CT_DIR = process.argv[2] ||
  "C:/Coding Repos/mhgu-collection-tracker/docs/data/materials";
const TREES = path.join(__dirname, "..", "docs", "data-trees.json");

if (!fs.existsSync(CT_DIR)) {
  console.error("Cannot find " + CT_DIR + "\nPass mhgu-collection-tracker's docs/data/materials path as an argument.");
  process.exit(1);
}
if (!fs.existsSync(TREES)) {
  console.error("Cannot find " + TREES + " — run build-trees.js first.");
  process.exit(1);
}

const challenge = JSON.parse(fs.readFileSync(TREES, "utf8"));
const byClass = new Map(challenge.map(c => [c.slug, c]));

let checked = 0, missing = [], mismatched = [];
for (const c of challenge) {
  const materialsPath = path.join(CT_DIR, c.slug + ".json");
  if (!fs.existsSync(materialsPath)) continue;   // e.g. classes CT tracks that this app doesn't
  const { parents = {} } = JSON.parse(fs.readFileSync(materialsPath, "utf8"));
  const byId = new Map(c.trees.map(t => [t.i, t.p || 0]));
  for (const [tidStr, truth] of Object.entries(parents)) {
    const tid = Number(tidStr);
    checked++;
    if (!byId.has(tid)) { missing.push({ slug: c.slug, tid, truth }); continue; }
    const got = byId.get(tid);
    const same = Array.isArray(truth) && Array.isArray(got) &&
      truth[0] === got[0] && truth[1] === got[1];
    if (!same) mismatched.push({ slug: c.slug, tid, truth, got });
  }
}

console.log(`checked ${checked} branch links across ${byClass.size} classes`);
for (const m of missing) console.log(`  MISSING  ${m.slug} tree ${m.tid} — collection-tracker says parent ${JSON.stringify(m.truth)}, data-trees.json has no such tree`);
for (const m of mismatched) console.log(`  MISMATCH ${m.slug} tree ${m.tid} — collection-tracker: ${JSON.stringify(m.truth)}, data-trees.json: ${JSON.stringify(m.got)}`);

if (missing.length || mismatched.length) {
  console.error(`\nFAIL: ${missing.length} missing, ${mismatched.length} mismatched. Re-run build-trees.js against a current mhgu-weapon-trees build.`);
  process.exit(1);
}
console.log("OK — data-trees.json's branch links match mhgu-collection-tracker exactly.");
